spring.application.name=auth-portal

spring.datasource.url=jdbc:postgresql://localhost:5435/catrion_auth
spring.datasource.username=catrion_user
spring.datasource.password=catrion_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

server.port=8080